### ISSUE TITLE
GOV.UK homepage search box not fully clickable without javascript

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/frontend#931]
See attached gif. When javascript is not available, the search area is smaller than the white area. If a user clicks on the right hand side, they can't action the box.

![govuk-no-js-search](https://cloud.githubusercontent.com/assets/2204224/13702672/370c44da-e788-11e5-9dc6-86fac758de6c.gif)

**Comment by tvararu** [comment]
After having a poke in the dev console, this should be addressable (naively, not thoroughly tested) using:

```diff
label {
- float: left;
+ position: absolute;
}

input {
- width: 50%;
+ width: 86%;
+ width: calc(100% - 37px);
}
```

**Comment by edwardhorsford** [comment]
The same issue exists for the header search box, FYI

**Comment by robinwhittleton** [comment]
`calc()` isn’t supported in IE8 unfortunately.

**Comment by nickcolley** [comment]
Could we simplify the input and use a placeholder coupled with a hidden label?

Guessing this was done because IE8 does not support placeholders, so could we show the hidden label on browsers that do not support placeholders, this would simplify a lot of the code here and make the search input a lot dumber.

How it'd look for legacy browsers that don't have placeholder support:

![screen shot 2016-05-25 at 10 45 28](https://cloud.githubusercontent.com/assets/2445413/15535561/d2aa690e-2265-11e6-897c-ee0b6ddde3e7.png)

**Comment by nickcolley** [comment]
Thanks @36degrees ! 🎉  https://github.com/alphagov/frontend/pull/1007
